[package]
name = "pulsarkey"
version = "1.4.1"
edition = "2024"
description = "Hardware-backed FIDO2 & Biometric Authentication Manager for Pop!_OS COSMIC"
repository = "https://github.com/mzia/PulsarKey"
homepage = "https://github.com/mzia/PulsarKey"
license = "MIT"
authors = ["M. Zia <mzia@pop-os.local>"]

[lib]
name = "pulsarkey"
path = "src/lib.rs"

[[bin]]
name = "pulsarkey"
path = "src/main.rs"

[[bin]]
name = "cosmic-fido2"
path = "src/main.rs"

[[bin]]
name = "pulsarkey-settings"
path = "src/gui_main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
colored = "3.1.1"
libc = "0.2.189"
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies]
ksni = "0.3.6"
